### ISSUE TITLE
Error at work

### ISSUE THREAD

**Issue by Brissan** [naifalshaye/chatgpt#3]
![image](https://github.com/naifalshaye/chatgpt/assets/5699121/0e107b80-fb8f-4a49-9f07-604e47601f14)

![image](https://github.com/naifalshaye/chatgpt/assets/5699121/013f6dba-72cc-43c2-9074-b9187d5cfd3b)

I installed everything according to the instructions, but I get this error

![image](https://github.com/naifalshaye/chatgpt/assets/5699121/038552fc-8b35-4189-bfcd-baa415c1b778)

The GET method is not supported for route nova-vendor/chatgpt/ask. Supported methods: POST.

**Comment by naifalshaye** [comment]
Hi Brssan,

Thanks for creating the issue.

The issue seems to be an API issue. 

I've added a try catch to handle any API errors such as, Incorrect API key or Exceeded API rate limit etc or any error returned from OpenAI API.

Also added another try catch to handle any general error when submit the question.

Upgrade the package:
composer upgrade naif/chatgpt

Make sure you have published the config file and added API key in .env file.

php artisan vendor:publish --provider="Naif\Chatgpt\ToolServiceProvider"  --force

It should work now or it will display what the issue is.

Thanks again.
